package com.medical.solution.dao;

public enum TablesCreatedTask {

	CREATE_DOCTOR, CREATE_PATIENT, CREATE_APPOINTMENT, CREATE_CALENDAR, CREATE_CASES, CREATE_CONTACT, CREATE_EXPERTISE, CREATE_LOGIN, CREATE_MESSAGE, CREATE_NOTIFICATION, CREATE_TODO_LIST
}
